name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make stormlib
      run: cd StormLib/build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DYNAMIC_MODULE=1 .. && make && sudo make install
    - name: make bncsutil
      run: cd ~/work/aura-bot/aura-bot/bncsutil/src/bncsutil/ && make && sudo make install
    - name: make aura-bot
      run: cd ~/work/aura-bot/aura-bot/ && make
