name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '[14.0,14.5)'
    - name: Build app for release
      run: msbuild aura.sln -t:rebuild -verbosity:diag -property:Configuration=Release
