name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: lib
      run: cd StormLib/build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DYNAMIC_MODULE=1 .. && make
    - name: make
      run: cd ~/work/aura-bot/aura-bot/bncsutil/src/bncsutil/ && make
    - name: make
      run: cd ~/work/aura-bot/aura-bot/src/ && make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
