name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add msvc-dev
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: win32
        sdk: 8.1
        vsversion: 2015
    - name: Build app for release
      run: cl aura.sln
